#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepumaWebApp.App_Data.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PUMASQL")]
	public partial class PumaSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblSalesType(tblSalesType instance);
    partial void UpdatetblSalesType(tblSalesType instance);
    partial void DeletetblSalesType(tblSalesType instance);
    partial void InserttblSalesRep(tblSalesRep instance);
    partial void UpdatetblSalesRep(tblSalesRep instance);
    partial void DeletetblSalesRep(tblSalesRep instance);
    #endregion
		
		public PumaSQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PUMASQLConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PumaSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PumaSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PumaSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PumaSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblSalesType> tblSalesTypes
		{
			get
			{
				return this.GetTable<tblSalesType>();
			}
		}
		
		public System.Data.Linq.Table<tblSalesRep> tblSalesReps
		{
			get
			{
				return this.GetTable<tblSalesRep>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSalesType")]
	public partial class tblSalesType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SalesType;
		
		private string _SalesDescription;
		
		private string _Updatedby;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private string _Createdby;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<bool> _ActiveFlag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalesTypeChanging(string value);
    partial void OnSalesTypeChanged();
    partial void OnSalesDescriptionChanging(string value);
    partial void OnSalesDescriptionChanged();
    partial void OnUpdatedbyChanging(string value);
    partial void OnUpdatedbyChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnCreatedbyChanging(string value);
    partial void OnCreatedbyChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnActiveFlagChanging(System.Nullable<bool> value);
    partial void OnActiveFlagChanged();
    #endregion
		
		public tblSalesType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SalesType
		{
			get
			{
				return this._SalesType;
			}
			set
			{
				if ((this._SalesType != value))
				{
					this.OnSalesTypeChanging(value);
					this.SendPropertyChanging();
					this._SalesType = value;
					this.SendPropertyChanged("SalesType");
					this.OnSalesTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDescription", DbType="NVarChar(255)")]
		public string SalesDescription
		{
			get
			{
				return this._SalesDescription;
			}
			set
			{
				if ((this._SalesDescription != value))
				{
					this.OnSalesDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SalesDescription = value;
					this.SendPropertyChanged("SalesDescription");
					this.OnSalesDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updatedby", CanBeNull=false)]
		public string Updatedby
		{
			get
			{
				return this._Updatedby;
			}
			set
			{
				if ((this._Updatedby != value))
				{
					this.OnUpdatedbyChanging(value);
					this.SendPropertyChanging();
					this._Updatedby = value;
					this.SendPropertyChanged("Updatedby");
					this.OnUpdatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby")]
		public string Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this.OnCreatedbyChanging(value);
					this.SendPropertyChanging();
					this._Createdby = value;
					this.SendPropertyChanged("Createdby");
					this.OnCreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveFlag")]
		public System.Nullable<bool> ActiveFlag
		{
			get
			{
				return this._ActiveFlag;
			}
			set
			{
				if ((this._ActiveFlag != value))
				{
					this.OnActiveFlagChanging(value);
					this.SendPropertyChanging();
					this._ActiveFlag = value;
					this.SendPropertyChanged("ActiveFlag");
					this.OnActiveFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSalesReps")]
	public partial class tblSalesRep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SalesRepID;
		
		private string _SalesRep;
		
		private string _SalesRepTitle;
		
		private System.Nullable<int> _Threshold;
		
		private string _BusinessType;
		
		private string _NSMID;
		
		private string _DSM;
		
		private System.Nullable<bool> _NewBizLine;
		
		private int _id;
		
		private string _Updatedby;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private string _Createdby;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<bool> _ActiveFlag;
		
		private System.Nullable<bool> _StackReport;
		
		private System.Nullable<System.DateTime> _Hiredate;
		
		private string _EmployeeID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalesRepIDChanging(string value);
    partial void OnSalesRepIDChanged();
    partial void OnSalesRepChanging(string value);
    partial void OnSalesRepChanged();
    partial void OnSalesRepTitleChanging(string value);
    partial void OnSalesRepTitleChanged();
    partial void OnThresholdChanging(System.Nullable<int> value);
    partial void OnThresholdChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnNSMIDChanging(string value);
    partial void OnNSMIDChanged();
    partial void OnDSMChanging(string value);
    partial void OnDSMChanged();
    partial void OnNewBizLineChanging(System.Nullable<bool> value);
    partial void OnNewBizLineChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUpdatedbyChanging(string value);
    partial void OnUpdatedbyChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnCreatedbyChanging(string value);
    partial void OnCreatedbyChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnActiveFlagChanging(System.Nullable<bool> value);
    partial void OnActiveFlagChanged();
    partial void OnStackReportChanging(System.Nullable<bool> value);
    partial void OnStackReportChanged();
    partial void OnHiredateChanging(System.Nullable<System.DateTime> value);
    partial void OnHiredateChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    #endregion
		
		public tblSalesRep()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SalesRepID
		{
			get
			{
				return this._SalesRepID;
			}
			set
			{
				if ((this._SalesRepID != value))
				{
					this.OnSalesRepIDChanging(value);
					this.SendPropertyChanging();
					this._SalesRepID = value;
					this.SendPropertyChanged("SalesRepID");
					this.OnSalesRepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRep", DbType="NVarChar(50)")]
		public string SalesRep
		{
			get
			{
				return this._SalesRep;
			}
			set
			{
				if ((this._SalesRep != value))
				{
					this.OnSalesRepChanging(value);
					this.SendPropertyChanging();
					this._SalesRep = value;
					this.SendPropertyChanged("SalesRep");
					this.OnSalesRepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepTitle", DbType="NVarChar(50)")]
		public string SalesRepTitle
		{
			get
			{
				return this._SalesRepTitle;
			}
			set
			{
				if ((this._SalesRepTitle != value))
				{
					this.OnSalesRepTitleChanging(value);
					this.SendPropertyChanging();
					this._SalesRepTitle = value;
					this.SendPropertyChanged("SalesRepTitle");
					this.OnSalesRepTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Threshold", DbType="Int")]
		public System.Nullable<int> Threshold
		{
			get
			{
				return this._Threshold;
			}
			set
			{
				if ((this._Threshold != value))
				{
					this.OnThresholdChanging(value);
					this.SendPropertyChanging();
					this._Threshold = value;
					this.SendPropertyChanged("Threshold");
					this.OnThresholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessType", DbType="NVarChar(50)")]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSMID", DbType="NVarChar(10)")]
		public string NSMID
		{
			get
			{
				return this._NSMID;
			}
			set
			{
				if ((this._NSMID != value))
				{
					this.OnNSMIDChanging(value);
					this.SendPropertyChanging();
					this._NSMID = value;
					this.SendPropertyChanged("NSMID");
					this.OnNSMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSM", DbType="NVarChar(255)")]
		public string DSM
		{
			get
			{
				return this._DSM;
			}
			set
			{
				if ((this._DSM != value))
				{
					this.OnDSMChanging(value);
					this.SendPropertyChanging();
					this._DSM = value;
					this.SendPropertyChanged("DSM");
					this.OnDSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewBizLine", DbType="Bit")]
		public System.Nullable<bool> NewBizLine
		{
			get
			{
				return this._NewBizLine;
			}
			set
			{
				if ((this._NewBizLine != value))
				{
					this.OnNewBizLineChanging(value);
					this.SendPropertyChanging();
					this._NewBizLine = value;
					this.SendPropertyChanged("NewBizLine");
					this.OnNewBizLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updatedby", DbType="VarChar(100)")]
		public string Updatedby
		{
			get
			{
				return this._Updatedby;
			}
			set
			{
				if ((this._Updatedby != value))
				{
					this.OnUpdatedbyChanging(value);
					this.SendPropertyChanging();
					this._Updatedby = value;
					this.SendPropertyChanged("Updatedby");
					this.OnUpdatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby", DbType="VarChar(100)")]
		public string Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this.OnCreatedbyChanging(value);
					this.SendPropertyChanging();
					this._Createdby = value;
					this.SendPropertyChanged("Createdby");
					this.OnCreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveFlag", DbType="Bit")]
		public System.Nullable<bool> ActiveFlag
		{
			get
			{
				return this._ActiveFlag;
			}
			set
			{
				if ((this._ActiveFlag != value))
				{
					this.OnActiveFlagChanging(value);
					this.SendPropertyChanging();
					this._ActiveFlag = value;
					this.SendPropertyChanged("ActiveFlag");
					this.OnActiveFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StackReport", DbType="Bit")]
		public System.Nullable<bool> StackReport
		{
			get
			{
				return this._StackReport;
			}
			set
			{
				if ((this._StackReport != value))
				{
					this.OnStackReportChanging(value);
					this.SendPropertyChanging();
					this._StackReport = value;
					this.SendPropertyChanged("StackReport");
					this.OnStackReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hiredate", DbType="Date")]
		public System.Nullable<System.DateTime> Hiredate
		{
			get
			{
				return this._Hiredate;
			}
			set
			{
				if ((this._Hiredate != value))
				{
					this.OnHiredateChanging(value);
					this.SendPropertyChanging();
					this._Hiredate = value;
					this.SendPropertyChanged("Hiredate");
					this.OnHiredateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(50)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
